### ISSUE TITLE
Missing target: T-Pro S

### ISSUE THREAD

**Issue by pfeerick** [ExpressLRS/targets#104]
No target/alias for Jumper T-Pro S

https://www.jumper-b2b.com/jumper-t-pro-internal-24g-1000mw-expresslrs-elrs-module-radio-controller-hall-sensor-gimbals-edgetx-opentx-p0114.html

**Comment by pfeerick** [comment]
Any progress / updates on this? This is available generally now from more retailers, so more people will be wanting a target for this soon.

**Comment by pkendall64** [comment]
What module does it use internally? I would assume it's just an alias for one of the others, but we have not seen it and Jumper have not asked us to add it either.

**Comment by pkendall64** [comment]
If you start wifi mode and add a screenshot of the banner section with the product name and version and also the hardware.json on the device we could verify which target it's an alias for. You can get the hardware.json file by going to the web interface and go to `/hardware.json`

**Comment by pfeerick** [comment]
I would think so too, as it is described as being the same as the TProV2 other than some handset (not RF) changes. I'll upload those when I get home.

**Comment by pfeerick** [comment]
Ok, so going back to my notes from May, it should have the same module as the T12-Max. 

![t-pro s](https://github.com/user-attachments/assets/ff6a2711-aa4e-4a3a-8cba-53840cc81ae4)

This is the json it shipped with:
[hardware_shipped_with.json](https://github.com/user-attachments/files/17549962/hardware_shipped_with.json)

This is the JSON I've been using with it (mostly just re-ordered to match T12 json, and fan dropped as it doesn't have one - although that then limits this to 500mw max power rather than the ... optimistic?... 1W it is rated at in the listings):
[Jumper T-Pro S.json](https://github.com/user-attachments/files/17550165/Jumper.T-Pro.S.json)

I have successfully flashed the backpack to 1.5.1 mis-using the T12 Max backpack target, but haven't used it other than to verify it reported it's version number back, and was able to start it's own WiFi AP. 

This is the `targets.json` snippet I've been using
```json
            "t-pro-s": {
                "product_name": "Jumper AION T-Pro S 2.4GHz TX",
                "lua_name": "AION T-Pro S TX",
                "layout_file": "Jumper T-Pro S.json",
                "upload_methods": ["uart", "wifi", "etx"],
                "min_version": "3.4.0",
                "platform": "esp32-s3",
                "firmware": "Unified_ESP32S3_2400_TX"
            },
```

**Comment by JyeSmith** [comment]
Fixed in https://github.com/ExpressLRS/targets/pull/120

**Comment by pfeerick** [comment]
Thanks Jye. It seems my sample was populated with a non-standard module, so the PR should be right. It appears that there will only be 2.4Ghz for the T-Pro S though, no 900Mhz planned.
