### ISSUE TITLE
50mW max telemetry output on Generic 900MHz RX?

### ISSUE THREAD

**Issue by ot0tot** [ExpressLRS/targets#118]
The SX1276 has a max telemetry output of 100mW, but the generic target seems to set the max output to 50mW. Is this intentional? Many manufacturers are advertising 100mW output from these receivers. 

https://github.com/ExpressLRS/targets/blob/dc8bd48b8316f3d895f848bf7026d49c0c7d2d99/RX/Generic%20900.json#L16

**Comment by pkendall64** [comment]
This target is designed for targets that that use the `PA_BOOST` output with an external PA.
Targets not using `PA_BOOST` and using the `RFO_HF` output can output up to 100mW.
In the case where a design uses the `RFO_HF` output then an overlay would be provided on the target that enables that output with `"radio_rfo_hf": true` and also specify the correct power values.
