### ISSUE TITLE
Add verified_hardware flag

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/targets#16]
We should bring back the user warning in expresslrs configurator for non verified hardware targets. In order to do that we need to add `"verified_hardware": false` to non verified hardware in our json files.

All `verifiedHardware: false` targets can be found in the configurator repo: https://github.com/ExpressLRS/ExpressLRS-Configurator/tree/7382bef4a6945d954946213febf5cdcc544f4f28/devices 

Related: https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/576

**Comment by pkendall64** [comment]
Personally I'm of the opinion we should remove all unsupported hardware from the targets all together. If the manufacturer can't be bothered sending a few samples for testing then why should we bother adding special support and special code to show the user that it's not verified!

**Comment by ot0tot** [comment]
Happy to do this if I can get a list of all hardware that has been verified by the devs.

**Comment by pkendall64** [comment]
Fixed in #61
