### ISSUE TITLE
Help IRX4

### ISSUE THREAD

**Issue by marcelking** [ExpressLRS/targets#90]
hello
Not sure if im in the right place i bought a irx4 lite expresslrs module but when i goto expresslrs configurator i cant find it in the target list of hardware? can anyone help i know this module has been around for a long time

regards

**Comment by pkendall64** [comment]
The irx4 lite is a 4-in-1 multi-protocol module NOT an ExpressLRS module.

**Comment by marcelking** [comment]
Hello
This is a Expresslrs module

**Comment by marcelking** [comment]
https://uk-m.banggood.com/IRangeX-iRX4-ExpressLRS-ELRS-2_4GHz-OpenTX-EdgeTX-Open-Source-Systems-Nano-TX-Module-for-Frsky-X-Lite-RadioMaster-Pocket-Jumper-T-PRO-Radio-Transmitter-p-2015399.html?akmClientCountry=GB

**Comment by pkendall64** [comment]
I see, they have different versions.
iRangeX is not a manufacturer that has worked with the development team, so there is no target for it.

**Comment by marcelking** [comment]
ok many thanks.

**Comment by pkendall64** [comment]
Sorry about that.
I would send it back and get something that is supported. When purchasing, you should check the configurator first to ensure that it is properly supported.
